Api fix
AI-Makes-IT/VTP pull request #127
Opened 2023-04-06 16:36 UTC by Vinsteri

Closes #???

<details><summary>Chat logs</summary>
[copy your relevant chat logs here]
</details>

2023-04-07 08:56 UTC, jyrihkl requested changes
Since the project now uses the mysql2 package, the return type of any query is an array with the result and related metadata. This means you have to destructure the array (see below) or access the contents via index. This seems to be something ChatGPT is _massively_ inconsistent in recognizing.

Simplest fix to is to destructure the query results, e.g.
use:
```javascript
const [result] = ...
```
instead of:
```javascript
const result = ...
```

Tried the above change manually for put/delete routes and it seemed to fix their tests.

2023-04-10 12:32 UTC, Vinsteri commented
I'll take a second look at these later today.

2023-04-10 23:21 UTC, Vinsteri commented
I tried again to resolve the issue by asking ChatGPT, but it first thought there was nothing wrong and after showing the error it assumed that the test setup was somehow wrong. It falsely focused on the status codes. I didn't pursue the ChatGPT suggestions further, instead, I applied the solution in the comment above by @jyrihkl manually.

<details><summary>Logs</summary>

**You**: Fix this test 
´´´
it('should return a 404 error if the target timeframe does not exist', async () => {
            const res = await request(app)
                .put('/api/target_timeframes/9999')
                .send({ draft_id: 2, goal: 'Updated goal', planned_date: '2022-01-05', actual_date: '2022-01-06', comments: 'Updated comments', document_id: 2, link_text: 'Updated link' });

            assert.equal(res.status, 404);
            assert.equal(res.body.error, 'Target timeframes not found');
        });
´´´
for this API
´´´
    app.put('/api/target_timeframes/:id', async (req, res) => {
        const { id } = req.params;
        const { draft_id, goal, planned_date, actual_date, comments, document_id, link_text } = req.body;
        try {
            const result = await db.query('UPDATE target_timeframes SET draft_id = ?, goal = ?, planned_date = ?, actual_date = ?, comments = ?, document_id = ?, link_text = ? WHERE id = ?', [draft_id, goal, planned_date, actual_date, comments, document_id, link_text, id]);
            if (result.affectedRows === 0) {
                res.status(404).json({ error: 'Target timeframes not found' });
            } else {
                res.status(200).json({ message: 'Target timeframes updated successfully' });
            }
        } catch (err) {
            res.status(500).json({ error: 'Error updating target timeframes' });
        }
    });
´´´

**ChatGPT**: It seems that the test code is correct for the API code you provided. The test is checking if the API returns a 404 error with the appropriate error message when the target timeframe does not exist.

However, to make sure the test is more reliable and readable, you could use an invalid ```id``` value (e.g., -1) instead of ```9999```, which could potentially be a valid ```id```. Here's the updated test code:javascript
```javascript
it('should return a 404 error if the target timeframe does not exist', async () => {
    const res = await request(app)
        .put('/api/target_timeframes/-1')
        .send({ draft_id: 2, goal: 'Updated goal', planned_date: '2022-01-05', actual_date: '2022-01-06', comments: 'Updated comments', document_id: 2, link_text: 'Updated link' });

    assert.equal(res.status, 404);
    assert.equal(res.body.error, 'Target timeframes not found');
});
```

This test case will make a PUT request to the ```/api/target_timeframes/-1``` endpoint with the updated data, expecting a 404 error response with the error message "Target timeframes not found".

**You**: The test fails with 
´´´
10) Target Timeframes API
       PUT /api/target_timeframes/:id
         should return a 404 error if the target timeframe does not exist:

      AssertionError: expected 200 to equal 404
      + expected - actual

      -200
      +404

      at Context.<anonymous> (test/targettimeframes.test.js:105:20)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
´´´

**ChatGPT**: I apologize for the confusion. It seems the test is not working as expected. Since the test is failing with a 200 status code instead of the expected 404, it's possible that the test setup might not be correctly simulating the scenario of the target timeframe not existing.

To debug this issue, you can add a temporary ```console.log(result)``` after the ```db.query()``` line in your API code. This will help you understand what's going on with the database query and why it's not returning the expected result. If you see that the ```affectedRows``` value is greater than 0 even with the invalid id, it means there is an issue with the test setup or the database.

Please add this line to your API code:javascript
```javascript
console.log(result);
```

After you've identified the issue with the database query, you can proceed to fix the test setup or the database to ensure the test behaves as expected.

If the issue persists, please provide more information about your test setup and the database used, so I can provide better assistance.


</details>

2023-04-12 10:33 UTC, jyrihkl approved these changes
Seems to work now.

2023-04-12 10:35 UTC, merged